hard_tabs = false
tab_spaces = 2

brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"

# Optional but nice:
indent_style = "Block"
reorder_imports = true
use_small_heuristics = "Max"
